### ISSUE TITLE
cosmic-swingset test flaking: Prometheus metric definitions

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#11175]
## Describe the bug

Today I began noticing spurious failures in the "Prometheus metric definitions" test.

[This PR](https://github.com/Agoric/agoric-sdk/pull/11166) just refactors tests, and while it fails on [test-cosmic-swingset (20.x)](https://github.com/Agoric/agoric-sdk/actions/runs/14112092780/job/39545160798#logs), it passes **test-cosmic-swingset (18.x)**. At first It thought it was some interaction with Node version, but the next one fails on 18.x and not 20.x.

[This PR](https://github.com/Agoric/agoric-sdk/pull/11170/files) does nothing with cosmic-swingset and [fails on it](https://github.com/Agoric/agoric-sdk/actions/runs/14116240596/job/39547188650?pr=11170):
```
not ok 5 - prometheus › Prometheus metric definitions %ava-dur=47414ms
#   compared 113 "#"-prefixed meta lines
#   compared 247 keys
#   compared 77 values
  ---
    name: AssertionError
    message: >-
      "heapStats_total_global_handles_size" values must match - direct 638[97](https://github.com/Agoric/agoric-sdk/actions/runs/14116240596/job/39547188650?pr=11170#step:6:98)6 vs.
      slog 630784
    assertion: is
    values:
      'Difference (- actual, + expected):': |-
        - 630784
        + 638976
    at: 'file://test/prometheus.test.js:174:9'
```

# Solution

I expect it's due to this PR that landed today,
- https://github.com/Agoric/agoric-sdk/pull/11132

**Comment by turadg** [comment]
Similar: https://github.com/Agoric/agoric-sdk/actions/runs/14207973219/job/39809795763?pr=11196#step:6:96

**Comment by turadg** [comment]
[Fresh encounter](https://github.com/Agoric/agoric-sdk/actions/runs/15174656718/job/42672568063?pr=11398),
```
not ok 6 - prometheus › Prometheus metric definitions %ava-dur=77263ms
  ---
    name: AssertionError
    message: Rejected promise returned by test
    values:
      'Rejected promise returned by test. Reason:': |-
        TypeError ***
          message: 'fetch failed',
        ***
    at: |-
      async file://test/prometheus.test.ts:77:20
      async file://test/prometheus.test.ts:71:40
  ...

```

**Comment by michaelfig** [comment]
Here's a different metric flake that @gibson042 has a solution for:

```
not ok 1 - Prometheus metric definitions %ava-dur=31066ms
#   compared 113 "#"-prefixed meta lines
#   compared 247 keys
#   "heapStats_total_heap_size" values must be within 20 % - direct 125739008 vs. slog 165437440
#   "heapStats_total_physical_size" values must be within 20 % - direct 124735488 vs. slog 165752832
#   "heapStats_malloced_memory" values must be within 50 % - direct 548968 vs. slog 1219584
#   "memoryUsage_heapTotal" values must be within 20 % - direct 125739008 vs. slog 165437440
#   "blockLagSeconds_sum" values must be within 0.5 s - direct 170445184.727 vs. slog 170445222.183
#   compared 77 values
  ---
    name: AssertionError
    message: '"heapStats_number_of_native_contexts" values must match - direct 1 vs. slog 2'
    assertion: is
    values:
      'Difference (- actual, + expected):': |-
        - 2
        + 1
    at: 'testPrometheusMetrics (file://test/prometheus.test.ts:222:9)'
  ...
```
