### ISSUE TITLE
Query transactions by events fails with `illegal base64 data`

### ISSUE THREAD

**Issue by michaelfig** [Agoric/Agoric#11257]
## Describe the bug

When attempting to query bank sends from a particular sender address, the `agd query txs ...` command fails. with an `illegal base64 data` error message.

## To Reproduce
1. Find a chain that you know has seen some `tx bank send` messages.
2. Run `agd q txs --limit=1 --events="message.action=/cosmos.bank.v1beta1.MsgSend" --node=https://<your-node>.rpc.agoric.net:443`
3. See `error in json rpc client... illegal base64 data...` as below:

```
Error: error in json rpc client, with http response metadata: (Status: 200 OK, Protocol HTTP/1.1). error unmarshalling result: illegal base64 data at input byte 4
Usage:
  agd query txs [flags]
...
```

## Expected behavior
I expected to see YAML transaction result output for a matching `MsgSend`, not an error.

<details><summary>Expected transaction results</summary>

```yaml
count: "1"
limit: "1"
page_number: "1"
page_total: "103"
total_count: "103"
txs:
- code: 0
  codespace: ""
  data: 12260A242F636F736D6F732E62616E6B2E763162657461312E4D736753656E64526573706F6E7365
  events:
  - attributes:
    - index: false
      key: c3BlbmRlcg==
      value: YWdvcmljMWhtNTR3cnhzdjhlM3BudzZseGo1bHNzZnBleG40OHh0ajZmaHh3
    - index: false
      key: YW1vdW50
      value: MTAwMDAwMHVibGQ=
    type: coin_spent
  - attributes:
    - index: false
      key: cmVjZWl2ZXI=
      value: YWdvcmljMWFlMGxtdHpsZ3JjbmxhOXhqa3BhYXJxNWQ1ZGZlejYzaDNudWNs
    - index: false
      key: YW1vdW50
      value: MTAwMDAwMHVibGQ=
    type: coin_received
  - attributes:
    - index: false
      key: cmVjaXBpZW50
      value: YWdvcmljMWFlMGxtdHpsZ3JjbmxhOXhqa3BhYXJxNWQ1ZGZlejYzaDNudWNs
    - index: false
      key: c2VuZGVy
      value: YWdvcmljMWhtNTR3cnhzdjhlM3BudzZseGo1bHNzZnBleG40OHh0ajZmaHh3
    - index: false
      key: YW1vdW50
      value: MTAwMDAwMHVibGQ=
    type: transfer
  - attributes:
    - index: false
      key: c2VuZGVy
      value: YWdvcmljMWhtNTR3cnhzdjhlM3BudzZseGo1bHNzZnBleG40OHh0ajZmaHh3
    type: message
  - attributes:
    - index: false
      key: ZmVl
      value: MTAwMDAwMHVibGQ=
    - index: false
      key: ZmVlX3BheWVy
      value: YWdvcmljMWhtNTR3cnhzdjhlM3BudzZseGo1bHNzZnBleG40OHh0ajZmaHh3
    type: tx
  - attributes:
    - index: false
      key: YWNjX3NlcQ==
      value: YWdvcmljMWhtNTR3cnhzdjhlM3BudzZseGo1bHNzZnBleG40OHh0ajZmaHh3LzA=
    type: tx
  - attributes:
    - index: false
      key: c2lnbmF0dXJl
      value: ZXZDQXQwOEF6Vmg2czRxRWlSQ1hSeHZjSS9USnh0NXNQb3hEUmFVUncxOE84OVExckNNNUtvMmhNR0V5Ti8ybU9ocjEyVFNrQVVIKzNvWHh1Z3dRVkE9PQ==
    type: tx
  - attributes:
    - index: false
      key: YWN0aW9u
      value: L2Nvc21vcy5iYW5rLnYxYmV0YTEuTXNnU2VuZA==
    - index: false
      key: c2VuZGVy
      value: YWdvcmljMWhtNTR3cnhzdjhlM3BudzZseGo1bHNzZnBleG40OHh0ajZmaHh3
    - index: false
      key: bW9kdWxl
      value: YmFuaw==
    type: message
  - attributes:
    - index: false
      key: c3BlbmRlcg==
      value: YWdvcmljMWhtNTR3cnhzdjhlM3BudzZseGo1bHNzZnBleG40OHh0ajZmaHh3
    - index: false
      key: YW1vdW50
      value: ODAwMDAwMDAwMDB1Ymxk
    type: coin_spent
  - attributes:
    - index: false
      key: cmVjZWl2ZXI=
      value: YWdvcmljMWZwY3Y5ZmZkcmp6YzJ2bnRkNXRtZnV5cXZ4Mno3N3MzNmQ3cmE3
    - index: false
      key: YW1vdW50
      value: ODAwMDAwMDAwMDB1Ymxk
    type: coin_received
  - attributes:
    - index: false
      key: cmVjaXBpZW50
      value: YWdvcmljMWZwY3Y5ZmZkcmp6YzJ2bnRkNXRtZnV5cXZ4Mno3N3MzNmQ3cmE3
    - index: false
      key: c2VuZGVy
      value: YWdvcmljMWhtNTR3cnhzdjhlM3BudzZseGo1bHNzZnBleG40OHh0ajZmaHh3
    - index: false
      key: YW1vdW50
      value: ODAwMDAwMDAwMDB1Ymxk
    type: transfer
  - attributes:
    - index: false
      key: c2VuZGVy
      value: YWdvcmljMWhtNTR3cnhzdjhlM3BudzZseGo1bHNzZnBleG40OHh0ajZmaHh3
    type: message
  gas_used: "82722"
  gas_wanted: "126690"
  height: "174"
  info: ""
  logs:
  - events:
    - attributes:
      - key: action
        value: /cosmos.bank.v1beta1.MsgSend
      - key: sender
        value: agoric1hm54wrxsv8e3pnw6lxj5lssfpexn48xtj6fhxw
      - key: module
        value: bank
      type: message
    - attributes:
      - key: spender
        value: agoric1hm54wrxsv8e3pnw6lxj5lssfpexn48xtj6fhxw
      - key: amount
        value: 80000000000ubld
      type: coin_spent
    - attributes:
      - key: receiver
        value: agoric1fpcv9ffdrjzc2vntd5tmfuyqvx2z77s36d7ra7
      - key: amount
        value: 80000000000ubld
      type: coin_received
    - attributes:
      - key: recipient
        value: agoric1fpcv9ffdrjzc2vntd5tmfuyqvx2z77s36d7ra7
      - key: sender
        value: agoric1hm54wrxsv8e3pnw6lxj5lssfpexn48xtj6fhxw
      - key: amount
        value: 80000000000ubld
      type: transfer
    - attributes:
      - key: sender
        value: agoric1hm54wrxsv8e3pnw6lxj5lssfpexn48xtj6fhxw
      type: message
    log: ""
    msg_index: 0
  raw_log: '[{"msg_index":0,"events":[{"type":"message","attributes":[{"key":"action","value":"/cosmos.bank.v1beta1.MsgSend"},{"key":"sender","value":"agoric1hm54wrxsv8e3pnw6lxj5lssfpexn48xtj6fhxw"},{"key":"module","value":"bank"}]},{"type":"coin_spent","attributes":[{"key":"spender","value":"agoric1hm54wrxsv8e3pnw6lxj5lssfpexn48xtj6fhxw"},{"key":"amount","value":"80000000000ubld"}]},{"type":"coin_received","attributes":[{"key":"receiver","value":"agoric1fpcv9ffdrjzc2vntd5tmfuyqvx2z77s36d7ra7"},{"key":"amount","value":"80000000000ubld"}]},{"type":"transfer","attributes":[{"key":"recipient","value":"agoric1fpcv9ffdrjzc2vntd5tmfuyqvx2z77s36d7ra7"},{"key":"sender","value":"agoric1hm54wrxsv8e3pnw6lxj5lssfpexn48xtj6fhxw"},{"key":"amount","value":"80000000000ubld"}]},{"type":"message","attributes":[{"key":"sender","value":"agoric1hm54wrxsv8e3pnw6lxj5lssfpexn48xtj6fhxw"}]}]}]'
  timestamp: "2025-04-08T00:43:41Z"
  tx:
    '@type': /cosmos.tx.v1beta1.Tx
    auth_info:
      fee:
        amount:
        - amount: "1000000"
          denom: ubld
        gas_limit: "126690"
        granter: ""
        payer: ""
      signer_infos:
      - mode_info:
          single:
            mode: SIGN_MODE_DIRECT
        public_key:
          '@type': /cosmos.crypto.secp256k1.PubKey
          key: ApbVlMcmEODtsa0hKbQDdfP6yDCVDtNsHfa0eJDYUlMm
        sequence: "0"
      tip: null
    body:
      extension_options: []
      memo: ""
      messages:
      - '@type': /cosmos.bank.v1beta1.MsgSend
        amount:
        - amount: "80000000000"
          denom: ubld
        from_address: agoric1hm54wrxsv8e3pnw6lxj5lssfpexn48xtj6fhxw
        to_address: agoric1fpcv9ffdrjzc2vntd5tmfuyqvx2z77s36d7ra7
      non_critical_extension_options: []
      timeout_height: "0"
    signatures:
    - evCAt08AzVh6s4qEiRCXRxvcI/TJxt5sPoxDRaURw18O89Q1rCM5Ko2hMGEyN/2mOhr12TSkAUH+3oXxugwQVA==
  txhash: 1EAAD4CD14585CA36319A037321F37238008A943EB84F32F46EBA546B909D1A0
 ```

</details>

## Platform Environment
 - what OS are you using? what version of Node.js? macOS 15.3.2, Node.js v20.17.0
 - is there anything special/unusual about your platform? not in this regard
 - what version of the Agoric-SDK are you using? fast-usdc-rc2-357-gaf84c3dd19

## Additional context
It only reproduces when there is at least one matching transaction for the `--events=...` filter on the RPC node `--node=...`.

There is no error if there are no matching transactions (such as with a typo in the event filter), just:
```
count: "0"
limit: "1"
page_number: "1"
page_total: "0"
total_count: "0"
txs: []
```

## Screenshots
n/a
