### ISSUE TITLE
otel collector no longer likes our traces

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#6513]
## Describe the bug

Our tracing exporter no longer works out of the box with the latest version of otelcol-contrib.  It does work with otelcol-contrib on version 0.50.0 however.

Testing otelcol-config:
```
receivers:
  otlp:
    protocols:
      http:
        endpoint:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: 
        - otlp
      exporters: 
        - logging
```

Config:
```
[Unit]
Description=Agoric Cosmos daemon
After=network-online.target

[Service]
User=ari
ExecStart=/home/ari/go/bin/agd start --log_level=warn
Restart=on-failure
RestartSec=3
LimitNOFILE=65536
Environment=OTEL_EXPORTER_PROMETHEUS_PORT=26661
Environment=SLOGFILE=/home/ari/.agoric/data/chain.slog
Environment=SLOGSENDER_AGENT=process
Environment=SLOGSENDER=@agoric/telemetry/src/otel-trace.js
Environment=OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4318/v1/traces
[Install]
WantedBy=multi-user.target
```

Expected behavior: 
- Spans will print to console when using https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.63.0
(Spans do print when using https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.50.0)

Observed behavior:
- Spans do not print at all or make it past ingest
