### ISSUE TITLE
#endo-branch: mechanism might be failing

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#8148]
## Describe the bug
Despite an `#endo-branch: markm-options-harmony`, PR https://github.com/Agoric/agoric-sdk/pull/8136 fails at https://github.com/Agoric/agoric-sdk/actions/runs/5766676498/job/15635200458?pr=8136#step:6:232 with 

```
> @agoric/swingset-xsnap-supervisor
$ yarn build:bundle
$ node scripts/build-bundle.js
Failed with (Error#1)
Error#1: 'environmentOptionsListHas' is not exported by ../../node_modules/@endo/env-options/index.js, imported by ../swingset-liveslots/src/virtualObjectManager.js
```

which is consistent with endo master, but not with endo branch `markm-options-harmony` from https://github.com/endojs/endo/pull/1710

I was able to verify this locally by `yarn link`ing my local agoric-sdk to my local endo's `@endo/env-options`. Once linked and rebuilt, the same local problem disappeared.

**Comment by michaelfig** [comment]
The major clues I found were in `test/cosmic-swingset` which did:

https://github.com/Agoric/agoric-sdk/actions/runs/5766676498/job/15635200458?pr=8136#step:6:21
```
At least package.json is newer than node_modules
[1/5] Validating package.json...
[2/5] Resolving packages...
[...]
```

That seemed to indicate our `bin/agd` script was rerunning `yarn install` even after the original installation had been done by an earlier job.  This can be patched by having CI not revert the changes made to the top level `package.json` and `yarn.lock`.

But it raises the question of how the timestamps got updated in the first place to trigger `bin/agd`'s build.  For that, I just looked a bit higher up in the run:

https://github.com/Agoric/agoric-sdk/actions/runs/5766676498/job/15635200458?pr=8136#step:4:27
```
Run actions/checkout@v3
  with:
    clean: false
    submodules: true
    persist-credentials: false
    path: .
    repository: Agoric/agoric-sdk
    token: ***
    ssh-strict: true
    sparse-checkout-cone-mode: true
    fetch-depth: 1
    lfs: false
    set-safe-directory: true
  env:
    AGORIC_AVA_USE_TAP: true
    TEST_COLLECT: tee -a _testoutput.txt
    NODE_V8_COVERAGE: coverage
    GH_ENGINE: 16.x
    ESM_DISABLE_CACHE: true
Syncing repository: Agoric/agoric-sdk
```

`agoric-sdk` was being checked out once to obtain the `restore-node` action, and then a second time within the `restore-node` action.  This could be avoided by accommodating the ubiquitous idiom:

```yml
      - uses: actions/checkout@v3
      - uses: ./.github/actions/restore-node
```

it looks like there was a bad parameter (`clean: 'false'` instead of `clean: false`) in `restore-node`'s own checkout that was tampering with the `package.json` timestamps. 

I'll do some testing and see if fixing both of those results in better behaviour.
