### ISSUE TITLE
vstore in A3P tests should be accessible to storage viewer

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#9052]
## What is the Problem Being Solved?

While debugging in an A3P test, it would be convenient to have access to the [p2p storage viewer](https://p2p-org.github.io/p2p-agoric-vstorage-viewer).

## Description of the Design

With @michaelfig's help we were able to identify two obstacles. 
 * The synthetic-chain tools should enable port 26657 [when starting the chain](https://github.com/Agoric/agoric-3-proposals/tree/main/packages/synthetic-chain/src/cli/run.ts)
 * CORS headers aren't being produced, so the viewer can't load the data once the above is addressed.

## Security Considerations

Test tooling shouldn't impact chain security.

## Scaling Considerations

N/A

## Test Plan

make it work for a3p tests.

## Upgrade Considerations

N/A

**Comment by michaelfig** [comment]
Enabling CORS can be done by changing the following in `$HOME/.agoric/config/config.toml` (or whatever the `--home` points to instead of `$HOME/.agoric`) to `cors_allowed_origins = ["*"]`:

```toml
[rpc]

# A list of origins a cross-domain request can be executed from
# Default value '[]' disables cors support
# Use '["*"]' to allow any origin
cors_allowed_origins = []
```
